### ISSUE TITLE
MDBDropdown has issue when using in react-styleguidist

### ISSUE THREAD

**Issue by jainam-shah-cygnet** [mdbootstrap/mdb-react-ui-kit#168]
I am facing issue in **MDBDropdown** component from the **mdb-react-ui-kit** package while using it with react-styleguidist.
Here when I click on Search Options the component disappears and shows error in console.

**NOTE** - I am using react version 17.0.2 and the latest version of mdb-react-ui-kit

![mdbdropdown-before-click](https://user-images.githubusercontent.com/80818983/156974333-7f6d3f92-f947-42cd-9bc3-a1214e1b7b36.png)

![mdbdropdown-after-click](https://user-images.githubusercontent.com/80818983/156974367-ddf974a4-ccbb-4c85-ad9b-05eeb47542c5.png)

![mdbdropdown-click](https://user-images.githubusercontent.com/80818983/156974390-b9130e28-3dc1-444b-82be-2c7afa84b925.png)

**Comment by krzysiu-w** [comment]
Hi!

Is it possible to share your code (at least the code of the whole MDBDropdown component and structure. The sample repository, or more code would be great)? I see the problem is with `React.cloneElement`, there are no elements to clone, so I think for now the problem is there.

Keep coding!

**Comment by jainam-shah-cygnet** [comment]
Hi @krzysiu-w 

Here I am sharing a zip of my sample code.

I have searched for the reason and found that when any null argument pass into **MDBDropdownItem** this issue occurs
`<MDBDropdownItem onClick={() => setIsShow(true)}>`
        `<span>Simple search</span>`
         `{isShow && (<i className='fas fa-check ml-2'></i>)} // The issue occurs here`
`</MDBDropdownItem>`
`<MDBDropdownItem onClick={() => setIsShow(false)}>`
        `<span>Extended search</span>`
         `{!isShow && (<i className='fas fa-check ml-2'></i>)} // The issue occurs here`
`</MDBDropdownItem>`

[mdbDropDownDemo.zip](https://github.com/mdbootstrap/mdb-react-ui-kit/files/8213511/mdbDropDownDemo.zip)

Thanks

**Comment by krzysiu-w** [comment]
Hi!

The problem is that your `MDBDropdownItem` component doesn't have any children if it is rendered conditionally. So when your `isShow` is `true` the second item is empty and if it has `false` - the first one, so the `React.cloneChild` can't map the children. To avoid that you can just render conditionally the whole item as I show below - it works perfectly :)

`<MDBDropdown>`
`  <MDBDropdownToggle className='btn btn-white waves-effect px-3 mr-2 ml-0 mt-0 mb-3 p-2 icon-btn'>`
`    <i className='fa fa-search mr-2 text-primary'></i>`
`    <span>Search options</span>`
`  </MDBDropdownToggle>`
`  <MDBDropdownMenu>`
`    <MDBDropdownItem onClick={() => console.log('click reload')}>`
`      <i className='fas fa-sync-alt mr-2'></i>`
`      <span>Refresh</span>`
`    </MDBDropdownItem>`
`    {isShow && (`
`      <MDBDropdownItem onClick={() => setIsShow(false)}>`
`        <span>Simple search</span>`
`        <i className='fas fa-check ml-2'></i>`
`      </MDBDropdownItem>`
`    )}`
`    {!isShow && (`
`      <MDBDropdownItem onClick={() => setIsShow(true)}>`
`        <span>Extended search</span>`
`        <i className='fas fa-check ml-2'></i>`
`      </MDBDropdownItem>`
`    )}`
`    <MDBDropdownItem`
`      onClick={() => console.log('click column chooser')}`
`    >`
`      <span>Select columns</span>`
`    </MDBDropdownItem>`
`  </MDBDropdownMenu>`
`</MDBDropdown>`

Keep coding!

**Comment by jainam-shah-cygnet** [comment]
Hi @krzysiu-w 

Thanks for the solution.

I have updated my code as you suggest, but my requirement is only toggle the icon, not the whole item.

And this is working fine with previous version (mdb4) and it's better to keep item and toggle only the icon on specific condition.

So kindly look into it.

Thanks

**Comment by krzysiu-w** [comment]
Hi!

That's a logical problem. When React checks this statement ` {isShow && (<i className='fas fa-check ml-2'></i>)}` it expects an additional node. So when the `isShow` state is set to false - `Array.cloneChild` tries to render a child that doesn't exist. To avoid that you also can use a ternary operator instead of logical AND one and return an, i.e., empty span like below:

`<MDBDropdownItem onClick={() => setIsShow(false)}>`
`  <span>Simple search</span>`
`  {isShow ? (`
`    <i className='fas fa-check ml-2'></i>`
`  ) : (`
`    <span></span>`
`  )}`
`</MDBDropdownItem>`

Keep coding!

**Comment by jainam-shah-cygnet** [comment]
Thanks @krzysiu-w
