### ISSUE TITLE
Build not working for production - White Page

### ISSUE THREAD

**Issue by praveenpandeyrepublic** [mdbootstrap/mdb-react-ui-kit#26]
### Mac book pro, Bootstrap 4.0.0

**Comment by praveenpandeyrepublic** [comment]
<img width="1680" alt="screen shot 2018-03-27 at 7 38 47 pm" src="https://user-images.githubusercontent.com/37839802/37972707-8906f84c-31f6-11e8-8b0f-1740c06d1b71.png">

**Comment by mattonit** [comment]
how can we reproduce this error? do you use free or pro version?

**Comment by praveenpandeyrepublic** [comment]
Hi Mattonit,

Please find the steps below -
1. Download the MDB Pro zip.
2.npm install
3.npm start -> Works fine on localhost

4.In package.json replace build:"webpack" to build: "react-scripts build" and run "npm run-script build".
observe the build folder is created.
5.use "serve -s build" to get the IP 
6. Paste the IP in the browser -> shows a empty index.html.

Does this require config changes for server deployment, we are new to React and MDBootstrap, we have been struggling with this issue without any result and help.

**Comment by smolenski-mikolaj** [comment]
Hi, 

First of all we suggest to make a build version with create-react-app. The steps to reproduce are the same as You wrote, just instead of downloading only our project You should add it to CRA as a dependency and then create Your own app.

This should work correctly:
1. npx create-react-app your-app-name && cd your-app-name
2. Add the necessary dependencies:
yarn add font-awesome@4.7.0 --exact
yarn add bootstrap@4.0.0 --exact
yarn add react-error-overlay@4.0.0 --exact
3. "mdbreact": "git+https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design.git"
4. yarn
5. Inside src/index.js file make the necessary imports right beneath the import ReactDOM... statement:
import 'font-awesome/css/font-awesome.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';
6. Import components you like and create Your own App
7. yarn build
8. cd build
9. npx serve

**Comment by vswood** [comment]
It seems quite odd to me that I would have to manually add font-awesome and other dependencies. I mean, if your package has dependencies, shouldn't they be part of the package install?
