### ISSUE TITLE
Input not updatable

### ISSUE THREAD

**Issue by wayne1203** [mdbootstrap/mdb-react-ui-kit#35]
I'm using 4.3.0 of mdbreact

I would like to clear the input value using state but not work.

Here is my code
```
this.setState({
   	heading: ""
});

<Input
    containerClass="col-12 input nopadding"
    hint="Heading"
    maxLength="20"
    value={this.state.heading}
    onChange={(value) => this.setState({heading: value.target.value})}
/>
```

It's work fine if I use HTML code, maybe componentWillReceiveProps problem?

```
<div class="md-form col-12 input nopadding">
    <input maxlength="20" type="text" class="form-control" placeholder="Heading"
        maxLength="20"
        value={this.state.heading}
        onChange={(value) => this.setState({heading: value.target.value})}/>
</div>
```

**Comment by smolenski-mikolaj** [comment]
Hi, the problem should be fixed with the next version of React (next week).

The following code might be helpful:

`<Input value={this.state.value} onChange={this.handleChange} label="Example label" />
 <Button onClick={this.handleSubmit}>Submit</Button>`

`  constructor(props) {
    super(props);
    this.state = {value: 'John Doe'};
    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(event) {
    this.setState({value: event.target.value});
  }`

Regards
