### ISSUE TITLE
 yarn run webpack 

### ISSUE THREAD

**Issue by chandrashekhar729** [mdbootstrap/mdb-react-ui-kit#60]
mdbreact@4.9.0 start C:\wamp\www\supportAdminreference
> yarn run webpack

'yarn' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdbreact@4.9.0 start: `yarn run webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdbreact@4.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shekhar\AppData\Roaming\npm-cache\_logs\2019-01-28T05_50_13_430Z-debug.log

**Comment by Rotarepmi** [comment]
Hi,

It looks like you do not have `Yarn` installed in your system. Check this link: https://yarnpkg.com/en/
We are using yarn on our config, but if you want to use only npm try to download our create-react-app template from here: https://mdbootstrap.com/docs/react/getting-started/download/

Because it is not an issue with mdbreact package I'm closing the issue.

Best regards,

jakub
