### ISSUE TITLE
mdbreact.esm.js crash Netlify build

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-react-ui-kit#74]
<img width="682" alt="Capture d’écran 2019-05-17 à 21 07 59" src="https://user-images.githubusercontent.com/44477769/57950547-de11d580-78e7-11e9-8071-18477768096c.png">

someone would have an idea of the problem ?

**Comment by AAndrasiuk** [comment]
Hi Sjarj,

This problem will be fixed in our upcoming release. 
But if you are a PRO user you already can use our branch `next` on GitLab where we fixed this issue. 

For detailed explanation why this error occurs you can read detailed explanation on our support channel : 

[https://mdbootstrap.com/support/react/update-to-4-14-breaks-website/  ](https://mdbootstrap.com/support/react/update-to-4-14-breaks-website/  )

Best regards.
