### ISSUE TITLE
pagination error when there is not image 

### ISSUE THREAD

**Issue by diegocruz9999** [mdbootstrap/mdb-react-ui-kit#76]
You can tap back and next button to change the page when you don't have any image on the library and when you do it the page goes white and have to reload the page

**Comment by tf-venegas10** [comment]
I have the same issue. For me it happens when the rows attribute is an empty array. The table is shown with no rows (as expected) showing 1 out of 0 pages on the pagination.
![image](https://user-images.githubusercontent.com/25334166/58712174-adb94500-8385-11e9-80da-4b8cfc0b1959.png)

 Alas, the next button is not disabled so when clicking it you can go forward and that enables the back button. The pagination passes to 0 of 0 an then, clicking the back button a couple of times can produce an error (cannot get .length of undefined) and the whole page crashes. 
![tempsnip](https://user-images.githubusercontent.com/25334166/58713523-5b2d5800-8388-11e9-94c8-8ee6a4fc3dc2.png)

![image](https://user-images.githubusercontent.com/25334166/58715056-b876d880-838b-11e9-9a64-02ab430af36e.png)
![image](https://user-images.githubusercontent.com/25334166/58715076-c3316d80-838b-11e9-9cb9-b25e67c19cdd.png)


I belive, this issue could be solved by disabling the next button on this case. By adding this validation to the PageItem on the DataTablePagination component. 
```
 <PageItem disabled={!pages.length || activePage === pages.length - 1}>
              <PageLink
                className="page-link"
                aria-label={label[1]}
                onClick={() => changeActivePage(activePage + 1)}
              >
                <span>{label[1]}</span>
              </PageLink>
            </PageItem>

```
Also, just for safety, we could disable the back button when activePage is -1 ( 0 of 0 case) by changing the === validation for a <= validation.  
```
 <PageItem disabled={activePage <= 0}>
              <PageLink
                className="page-link"
                aria-label={label[0]}
                onClick={() => changeActivePage(activePage - 1)}
              >
                    <span>{label[0]}</span>
              </PageLink>
</PageItem>
```

**Comment by tf-venegas10** [comment]
I created a pull request with what I think is the solution

**Comment by kalifa17** [comment]
Please can we merge this PR? its a good solution and I also need the solution for this issue! thanks

**Comment by AAndrasiuk** [comment]
Hi, 

We changed the code of DataTablePagination component according to [tf-venegas10](https://github.com/tf-venegas10) solution. 

Thank you for help in improving our product!
