### ISSUE TITLE
Add Roboto-Black font and extend font-weight utility

### ISSUE THREAD

**Issue by cgero-eth** [mdbootstrap/mdb-react-ui-kit#87]
Would it be possible to add the Roboto-Black font and extend the font-weight utility with the font-weight-thin, font-weight-medium and font-weight-black classes?

**Comment by kstepien3** [comment]
Hi @RuggeroCino,

About `font-weight-thin`, `font-weight-medium` and `font-weight-black` we encourage you to use `font-weight-light`, `font-weight-lighter` and `font-weight-bolder`, can use these classes in your projects because MDB uses styles from Bootstrap. 

 

> Would it be possible to add the Roboto-Black font

For this time we encourage you to personally import font. If it changes we will write about it on [GitHub Commits ](https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/commits/master) and [MDBootsrap changelog](https://mdbootstrap.com/docs/react/changelog/) page.

Best regards, Konrad.
