### ISSUE TITLE
Active class assigned twice

### ISSUE THREAD

**Issue by StanislavBerezin** [mdbootstrap/mdb-react-ui-kit#95]
There is a problem with the package, not sure why but just copying the code from your docs (https://mdbootstrap.com/docs/react/components/tabs/) doesnt seem to work and class active assigned twice? any reason its behaving this way?
![Screenshot from 2019-12-15 23-41-19](https://user-images.githubusercontent.com/33718805/70863494-7eba9780-1f94-11ea-83e7-2a905233df5b.png)

P.s the code is copied directly from your website

**Comment by pglejzer** [comment]
Yes, there is a bug with our component `MDBNavLink`.  This bug is showing because MDBNavLink has a bad structure about importing a wrong component from `react-router-dom`. In that of kind component like tabs, it should be a normal `Link` but there is not. 

I already make a new component of what is called `MDBLink` and this will fix this bug. This component will be available in your package in the new release in the next Monday (23th of December). 

If you want to fix this now you have to add prop `link` to MDBNavLink. This is a workaround about that at the moment. Sorry about this bug. Have a nice day!

**Comment by pglejzer** [comment]
This bug will be resolved in our future release. I close it now. Thanks.
